export const products = [
  {
    id: 1,
    name: "Wireless Noise-Cancelling Headphones",
    score: 52,
    status: "bad",
    category: "Electronics",
    price: "$89.99",
    aiSummary: "AI agents struggle to confidently recommend this product due to missing schema and thin description.",
    dimensions: {
      description: 48,
      schema: 12,
      images: 55,
      brandVoice: 70,
      comparability: 38,
      trustSignals: 60,
    },
    issues: [
      { severity: "critical", text: "Missing Product + Offer JSON-LD schema", action: "Add JSON-LD markup" },
      { severity: "critical", text: "Description under 80 words — too thin for AI comprehension", action: "Expand description" },
      { severity: "warning",  text: "No frequency response or driver specs listed", action: "Add spec table" },
      { severity: "info",     text: "Only 3 reviews — aggregate rating not surfaced", action: "Add aggregate rating" },
    ],
  },
  {
    id: 2,
    name: "Running Shoes Pro X2",
    score: 49,
    status: "bad",
    category: "Footwear",
    price: "$114.00",
    aiSummary: "Waterproof claims exist but lack supporting attributes. AI agents can't verify specs, hurting recommendation confidence.",
    dimensions: {
      description: 60,
      schema: 40,
      images: 50,
      brandVoice: 55,
      comparability: 30,
      trustSignals: 45,
    },
    issues: [
      { severity: "critical", text: "No terrain compatibility attributes in schema", action: "Add terrain tags" },
      { severity: "critical", text: "Waterproof claim not backed by structured spec", action: "Add waterproofing spec" },
      { severity: "warning",  text: "Missing arch support and drop height details", action: "Update product specs" },
      { severity: "info",     text: "No size guide linked from product page", action: "Link size guide" },
    ],
  },
  {
    id: 3,
    name: "Smart Watch Series 5",
    score: 94,
    status: "great",
    category: "Electronics",
    price: "$249.00",
    aiSummary: "Excellent AI visibility. Rich schema, detailed specs, and strong review signals make this a top recommendation candidate.",
    dimensions: {
      description: 95,
      schema: 92,
      images: 88,
      brandVoice: 96,
      comparability: 91,
      trustSignals: 94,
    },
    issues: [
      { severity: "info", text: "Alt text on 2 images could be more descriptive", action: "Improve alt text" },
    ],
  },
  {
    id: 4,
    name: "Laptop Backpack 30L",
    score: 87,
    status: "good",
    category: "Accessories",
    price: "$64.99",
    aiSummary: "Good visibility overall. Minor copy inconsistency across variants slightly reduces AI confidence in brand voice.",
    dimensions: {
      description: 88,
      schema: 82,
      images: 90,
      brandVoice: 72,
      comparability: 85,
      trustSignals: 88,
    },
    issues: [
      { severity: "warning", text: "Brand voice inconsistency across colour variants", action: "Standardise copy" },
      { severity: "info",    text: "Laptop compatibility list not structured as schema", action: "Add compatibility schema" },
    ],
  },
  {
    id: 5,
    name: "USB-C Hub 7-in-1",
    score: 78,
    status: "good",
    category: "Electronics",
    price: "$39.99",
    aiSummary: "Solid base but missing comparison attributes. AI agents place it lower when users ask for spec comparisons.",
    dimensions: {
      description: 80,
      schema: 74,
      images: 82,
      brandVoice: 78,
      comparability: 55,
      trustSignals: 76,
    },
    issues: [
      { severity: "warning", text: "Weight, dimensions and compatibility not in schema", action: "Add spec table" },
      { severity: "warning", text: "Price not exposed in structured data", action: "Update schema" },
    ],
  },
  {
    id: 6,
    name: "Mechanical Keyboard TKL",
    score: 63,
    status: "warn",
    category: "Electronics",
    price: "$129.00",
    aiSummary: "Mid-tier visibility. Key spec gaps and missing schema fields cause AI agents to deprioritise this product in comparisons.",
    dimensions: {
      description: 65,
      schema: 50,
      images: 70,
      brandVoice: 68,
      comparability: 52,
      trustSignals: 62,
    },
    issues: [
      { severity: "critical", text: "Switch type not in structured data", action: "Add switch schema" },
      { severity: "warning",  text: "No actuation force or travel distance listed", action: "Add key specs" },
      { severity: "warning",  text: "Price missing from JSON-LD Offer", action: "Update schema" },
      { severity: "info",     text: "Layout (TKL) not explicitly stated in title", action: "Update title" },
    ],
  },
  {
    id: 7,
    name: "Portable Charger 20000mAh",
    score: 81,
    status: "good",
    category: "Electronics",
    price: "$44.99",
    aiSummary: "Good structured data coverage. Review count low but description and specs are AI-friendly.",
    dimensions: {
      description: 85,
      schema: 80,
      images: 78,
      brandVoice: 82,
      comparability: 79,
      trustSignals: 58,
    },
    issues: [
      { severity: "warning", text: "Review count too low — aggregate rating not surfaced", action: "Add aggregate rating" },
      { severity: "info",    text: "Charging speed not listed as structured attribute", action: "Add charging spec" },
    ],
  },
];

export const simulationData = {
  query: "Best waterproof hiking shoes under $120",
  agentModel: "GPT-4o Shopping",
  rankedAt: 3,
  totalResults: 12,
  confidenceScore: 71,
  positives: [
    { title: "Waterproof claim present", detail: "Product description explicitly states waterproof construction, matching query intent." },
    { title: "Price within range", detail: "Listed at $114.00 — clearly within the $120 budget constraint." },
    { title: "Category schema detected", detail: "Product schema correctly categorised as footwear with outdoor use case." },
  ],
  gaps: [
    { title: "Missing terrain compatibility", detail: "No trail/hiking terrain tags. AI agents rank shoes with explicit terrain data higher for hiking queries." },
    { title: "No waterproofing standard cited", detail: "Claims waterproof but doesn't reference IPX rating or Gore-Tex — reduces agent confidence." },
    { title: "Arch support details absent", detail: "Competing products include arch support and drop height. Adding these improves comparison rank." },
    { title: "No trail-specific review keywords", detail: "Reviews don't mention trails or terrain — agents use review signals for intent matching." },
  ],
  competitorComparison: [
    { name: "TrailMaster Waterproof Boot", score: 91, reason: "IPX7 rating, terrain tags, arch spec" },
    { name: "HydroStep Pro",              score: 84, reason: "Gore-Tex label, 200+ trail reviews" },
    { name: "Running Shoes Pro X2",       score: 71, reason: "Your product — waterproof claim only" },
    { name: "AquaRun Lite",               score: 68, reason: "Lower price but thin description" },
  ],
  suggestedQueries: [
    "Waterproof hiking shoes Gore-Tex",
    "Trail running shoes under $150",
    "Best shoes for wet terrain hiking",
  ],
};

export const dashboardData = {
  aiReadinessScore: 84,
  discoverabilityScore: 67,
  trustScore: 91,
  comparisonScore: 58,

  weeklyDeltas: {
    aiReadiness: +6,
    discoverability: +3,
    trust: -1,
    comparison: +11,
  },

  issueBreakdown: [
    { category: "Product Descriptions", score: 88, issues: 4, color: "#16b98c" },
    { category: "Structured Data", score: 62, issues: 9, color: "#f5b429" },
    { category: "Brand Voice", score: 75, issues: 6, color: "#4d7aff" },
    { category: "Image Alt Text", score: 41, issues: 18, color: "#f0683a" },
    { category: "Meta / SEO Tags", score: 79, issues: 3, color: "#8b6ef5" },
  ],

  recentIssues: [
    { id: 1, severity: "critical", product: "Wireless Noise-Cancelling Headphones", issue: "Missing structured data schema (Product, Offer)", action: "Add JSON-LD markup" },
    { id: 2, severity: "critical", product: "Running Shoes Pro X2", issue: "Product description too short for AI comprehension (<80 words)", action: "Expand description" },
    { id: 3, severity: "critical", product: "Smart Watch Series 5", issue: "No alt text on 6 product images", action: "Add alt text" },
    { id: 4, severity: "critical", product: "Laptop Backpack 30L", issue: "Brand voice inconsistency detected across variants", action: "Standardise copy" },
    { id: 5, severity: "warning", product: "USB-C Hub 7-in-1", issue: "Comparison attributes missing (weight, dimensions, compatibility)", action: "Add spec table" },
    { id: 6, severity: "warning", product: "Mechanical Keyboard TKL", issue: "Price not exposed in structured data", action: "Update schema" },
    { id: 7, severity: "info", product: "Portable Charger 20000mAh", issue: "Review count not surfaced to AI agents", action: "Add aggregate rating" },
  ],

  weeklyTrend: [
    { day: "Mon", score: 71 },
    { day: "Tue", score: 73 },
    { day: "Wed", score: 72 },
    { day: "Thu", score: 76 },
    { day: "Fri", score: 79 },
    { day: "Sat", score: 81 },
    { day: "Sun", score: 84 },
  ],

  topProducts: [
    { name: "Smart Watch Series 5", score: 94, status: "great" },
    { name: "Laptop Backpack 30L", score: 87, status: "good" },
    { name: "USB-C Hub 7-in-1", score: 78, status: "good" },
    { name: "Mechanical Keyboard TKL", score: 63, status: "warn" },
    { name: "Running Shoes Pro X2", score: 49, status: "bad" },
  ],
};